version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
   #base-directory: 'target/'
  files:
    - target/my-app.war
    - buildspec.yml
    - appspec.yml
    - scripts
  discard-paths: yes
